name: Discord Webhook Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Total Commits
        id: count
        run: |
          echo "total=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-color: 3447003
          content: "😎️😏️🏗️💯️💻️🔥️: @everyone, MAIS UM BRABO DEU COMMIT!"
          embed-description: |
            O brabo ```fix
            ${{ github.actor }}
            ``` fez o commit ```diff
            + ${{ github.event.head_commit.message }}
            ``` no repo ```ini
            [${{ github.repository }}]
            ``` as ```bash
            "${{ github.event.head_commit.timestamp }}"
            ```!! Esse é o commit número ```yaml
            ${{ steps.count.outputs.total }}
            ``` do repo.
